# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftNetTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftNetTest
  pod 'Alamofire'
  pod 'SwiftyNet', '~> 1.0.0'
  
  target 'SwiftNetTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftNetTestUITests' do
    # Pods for testing
  end

end
